# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "linkedin"
    name       = "LinkedIn"
    url        = "https://www.linkedin.com/in/adir-morgan"

    [social.params]
        icon = "linkedin"


[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/adirmorgan"

    [social.params]
        icon = "github"

[[social]]
    identifier = "scholar"
    name       = "Scholar"
    url        = "https://scholar.google.co.il/citations?user=qjv-FMoAAAAJ&hl=iw"

    [social.params]
        icon = "google-scholar"